### ISSUE TITLE
train video classification with multi-gpu support

### ISSUE THREAD

**Issue by dragen1860** [facebookresearch/pytorchvideo#101]
Dear all:
  I succeed to run `python train.py` on single GPU card. However, when i try to set pytorch-lightning with `gpus=4` on 4 gpu cards, it trigger the following errors:

```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
/media/sdf/long/conda/envs/pytorchvideo/lib/python3.7/site-packages/deprecate/deprecation.py:115: LightningDeprecationWarning: The `Accuracy` was deprecated since v1.3.0 in favor of `torchmetrics.classification.accuracy.Accuracy`. It will be removed in v1.5.0.
  stream(template_mgs % msg_args)
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]
Traceback (most recent call last):
  File "train.py", line 507, in <module>
    main()
  File "train.py", line 486, in main
    train(args)
  File "train.py", line 494, in train
    trainer.fit(classification_module, data_module)
  File "/media/sdf/long/conda/envs/pytorchvideo/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/media/sdf/long/conda/envs/pytorchvideo/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/media/sdf/long/conda/envs/pytorchvideo/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/media/sdf/long/conda/envs/pytorchvideo/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/media/sdf/long/conda/envs/pytorchvideo/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 122, in start_training
    mp.spawn(self.new_process, **self.mp_spawn_kwargs)
  File "/media/sdf/long/conda/envs/pytorchvideo/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/media/sdf/long/conda/envs/pytorchvideo/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 179, in start_processes
    process.start()
  File "/media/sdf/long/conda/envs/pytorchvideo/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/media/sdf/long/conda/envs/pytorchvideo/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/media/sdf/long/conda/envs/pytorchvideo/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/media/sdf/long/conda/envs/pytorchvideo/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/media/sdf/long/conda/envs/pytorchvideo/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/media/sdf/long/conda/envs/pytorchvideo/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7f14c1564290>: attribute lookup <lambda> on pytorchvideo.models.resnet failed

```

Has anyone succeed to run video classification with multi-gpu training？ Thank you.

**Comment by anisaha1** [comment]
Hi, @dragen1860,

replace your Lambda() in transforms with a dedicated function.

e.g. if you have 
```python 
Lambda(lambda x: x / 255.0)
```

replace it with

```python
def lambda_tmp(x):
    return (x / 255.0)
Lambda(lambda_tmp)
```

[Look at this issue.](https://discuss.pytorch.org/t/cant-pickle-local-object-dataloader-init-locals-lambda/31857/10)

**Comment by lennart7** [comment]
Looks like several tutorials still use lambdas
https://pytorchvideo.org/#quickstart
https://pytorchvideo.org/docs/tutorial_classification
