### ISSUE TITLE
NameError: name 'LabeledVideoPaths' is not defined

### ISSUE THREAD

**Issue by SungmanHong** [facebookresearch/pytorchvideo#147]
Hi, i got error of nameError

when do train.py

here is my log...

Traceback (most recent call last):
  File "train.py", line 9, in <module>
    import pytorchvideo.data
  File "/home/hsm/test/se2/pytorchvideo/data/__init__.py", line 3, in <module>
    from .ava import Ava  # noqa
  File "/home/hsm/test/se2/pytorchvideo/data/ava.py", line 11, in <module>
    from pytorchvideo.data.labeled_video_dataset import LabeledVideoDataset
  File "/home/hsm/test/se2/pytorchvideo/data/labeled_video_dataset.py", line 12, in <module>
    from .labeled_video_paths import LabeledVideoPaths
  File "/home/hsm/test/se2/pytorchvideo/data/labeled_video_paths.py", line 13, in <module>
    class LabeledVideoPaths:
  File "/home/hsm/test/se2/pytorchvideo/data/labeled_video_paths.py", line 19, in LabeledVideoPaths
    def from_path(cls, data_path: str) -> LabeledVideoPaths:
NameError: name 'LabeledVideoPaths' is not defined

**Comment by kalyanvasudev** [comment]
@SungmanHong, I can seem to be able to reproduce this error. Were you able to fix it?

**Comment by kalyanvasudev** [comment]
Please re-open the issue if the problem persists.

**Comment by ajaichemmanam** [comment]
Its because pytorchvideo was not installed. Please install and try again.
